// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dbtest.web;

import com.dbtest.service.api.HelloDbService;
import com.dbtest.web.HelloDbsItemJsonController;

privileged aspect HelloDbsItemJsonController_Roo_Controller {
    
    /**
     * TODO Auto-generated attribute documentation
     */
    public HelloDbService HelloDbsItemJsonController.helloDbService;
    
}
